// SPDX-License-Identifier: MIT
// Copyright (c) 2026 viaGraph B.V. (Whisper Security)
//
// GENERATED by scripts/gen-graph.mjs from the Whisper catalog. Do not edit by hand: change
// the catalog (or the generator) and re-run `node scripts/gen-graph.mjs`.
//
// The KEYED GRAPH namespace: the Whisper security graph, one typed method per catalog verb,
// POSTed to graph.whisper.security/api/query. It is Cypher, so it is KEYED (Kaveh's rule:
// if it is Cypher it needs an API key). This is the SAME auth path as the control plane,
// the key travels only as X-API-Key, never in a URL or a log. The keyless surface
// (verify / resolve / rdap) stays pure HTTPS and never touches this namespace.
//
// Wire shape: the graph endpoint replies { columns, rows, statistics } where each row is an
// OBJECT keyed by column name, so this namespace parses that object-row shape itself and
// returns a GraphResult; it does NOT route through the control-plane envelope decoder
// (that one expects array-rows and would silently mangle these results). Pure fetch, zero
// dependencies.

import { WhisperError, doFetch, parseJson, readCappedText, resolveFetch } from "./http.js";
import { endpointsFor } from "./keyless.js";
import type {
  FlowParams,
  FlowResult,
  FlowStep,
  GraphParams,
  GraphResult,
  GraphStatistics,
  RequestOptions,
} from "./types.js";

const USER_AGENT = "whisper-edge/0.3";

/** Options for creating a graph client (same shape as the rest of the SDK). */
export interface GraphOptions extends RequestOptions {}

interface RawGraphBody {
  columns?: unknown;
  rows?: unknown;
  statistics?: unknown;
  detail?: unknown;
  title?: unknown;
}

/** Normalise the graph endpoint's object-row envelope into a {@link GraphResult}. */
function decodeGraph(body: unknown, status: number): GraphResult {
  const o = (body && typeof body === "object" ? body : {}) as RawGraphBody;
  const columns = Array.isArray(o.columns) ? o.columns.map((c) => String(c)) : [];
  const rows = Array.isArray(o.rows)
    ? o.rows.map((r) => (r && typeof r === "object" && !Array.isArray(r) ? (r as Record<string, unknown>) : { value: r }))
    : [];
  const statistics = (o.statistics && typeof o.statistics === "object" ? o.statistics : {}) as GraphStatistics;
  return { columns, rows, statistics, raw: body, status };
}

/**
 * The Whisper security graph, authenticated with an owner API key. Every method runs one
 * catalog verb. Direct verbs POST a parameterised Cypher read to /api/query and return a
 * {@link GraphResult}; flow verbs (multi-step investigations) run through the gallery
 * runner over SSE and return the aggregated {@link FlowResult}. The raw {@link query}
 * escape hatch runs arbitrary Cypher. Reachable both standalone via graph(key) and as
 * control(key).graph, bound to the same key.
 */
export class WhisperGraph {
  private readonly key: string;
  private readonly opts: GraphOptions;

  constructor(apiKey: string, opts: GraphOptions = {}) {
    const k = (apiKey ?? "").trim();
    if (k === "") {
      throw new WhisperError("no API key, the graph is keyed, pass your whisper_live_ key (never hard-code it; read it from the environment)", { status: 401 });
    }
    this.key = k;
    this.opts = opts;
  }

  private merge(extra?: RequestOptions): RequestOptions {
    return { ...this.opts, ...extra, endpoints: { ...this.opts.endpoints, ...extra?.endpoints } };
  }

  /**
   * POST a parameterised Cypher read to the graph endpoint and decode the object-row
   * envelope. `params` are bound server-side as $-parameters (never spliced into the query),
   * so a value can never break out of the Cypher, however hostile. The key rides only as
   * the X-API-Key header. Any >=400 status surfaces the server's clear detail as a
   * WhisperError (Postel: a clear error, never an opaque 500).
   */
  private async runDirect(cypher: string, params: GraphParams, reqOpts?: RequestOptions): Promise<GraphResult> {
    const o = this.merge(reqOpts);
    const url = endpointsFor(o).control;
    const resp = await doFetch(
      url,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "application/json",
          "user-agent": USER_AGENT,
          "x-api-key": this.key,
        },
        body: JSON.stringify({ query: cypher, parameters: params }),
      },
      o,
      "graph",
    );
    const text = await readCappedText(resp);
    const body = parseJson(text, "graph", resp.status);
    if (resp.status >= 400) {
      const p = (body && typeof body === "object" ? body : {}) as Record<string, unknown>;
      const detail = typeof p.detail === "string" ? p.detail : typeof p.title === "string" ? p.title : `graph returned status ${resp.status}`;
      throw new WhisperError(detail, {
        status: resp.status,
        detail: typeof p.detail === "string" ? p.detail : undefined,
        title: typeof p.title === "string" ? p.title : undefined,
        type: typeof p.type === "string" ? p.type : undefined,
      });
    }
    return decodeGraph(body, resp.status);
  }

  /**
   * The raw escape hatch: run an arbitrary Cypher read against the graph with your own
   * `params` (bound as $-parameters). KEYED. Use this for any query the catalog does not
   * name, or a bespoke form of a named verb (e.g. a submit `feedback` with the full
   * optional field set, or an `UNWIND $records` batch submit).
   */
  query(cypher: string, params: GraphParams = {}, reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect(cypher, params, reqOpts);
  }

  /**
   * Run a catalog FLOW (a multi-step investigation) through the gallery runner and
   * aggregate its Server-Sent-Events stream into a {@link FlowResult}. `inputs` are the
   * flow's typed entities keyed by name; the FIRST is the anchor the graph is built around,
   * every other input rides in the run's params. `params` are the flow's tunable knobs
   * (level / depth / instanceType, ...). KEYED: the key travels only as X-API-Key. Pass
   * `reqOpts.onFlowEvent` to observe each SSE event as it arrives (progressive rendering);
   * the returned promise still resolves with the full aggregate. An `error` event, or any
   * >=400, surfaces as a clear WhisperError (Postel: a clear error, never an opaque 500).
   * The default timeout is 120s (flows are multi-step); override via `reqOpts.timeoutMs`.
   */
  async runFlow(
    slug: string,
    inputs: Record<string, string | string[]> = {},
    params: FlowParams = {},
    reqOpts?: RequestOptions,
  ): Promise<FlowResult> {
    const o = this.merge(reqOpts);
    const url = endpointsFor(o).flowRun;

    // The runner's wire contract is {slug, value, paramValues}: `value` is the ONE primary
    // entity (a host / IP / ASN), or `values` for a bulk list; `paramValues` carries every
    // other input plus every tuning knob. So the FIRST input becomes the anchor `value`, and
    // every other input and every flow param rides in `paramValues`. A nullish input is
    // skipped so the flow's own default applies (Postel: sensible defaults, liberal in what
    // we accept). We send ONLY the keys the runner reads: an `inputs`/`params` map is
    // silently ignored, so the flow would fall back to its default anchor.
    const paramValues: Record<string, unknown> = {};
    let value: string | undefined;
    let values: string[] | undefined;
    let first = true;
    for (const [name, val] of Object.entries(inputs)) {
      if (val === undefined || val === null) continue;
      if (first) {
        if (Array.isArray(val)) values = val.map((x) => String(x));
        else value = String(val);
        first = false;
      } else {
        paramValues[name] = val;
      }
    }
    for (const [k, v] of Object.entries(params)) paramValues[k] = v;
    const body: Record<string, unknown> = { slug };
    if (value !== undefined) body.value = value;
    if (values !== undefined) body.values = values;
    if (Object.keys(paramValues).length > 0) body.paramValues = paramValues;

    // A flow is a long-lived SSE read, so we drive the timeout + abort ourselves (doFetch's
    // one-shot timeout would abort mid-stream). The clock covers the whole run.
    const f = resolveFetch(o);
    const timeoutMs = o.timeoutMs ?? 120_000;
    const ac = new AbortController();
    const onAbort = () => ac.abort((o.signal as AbortSignal).reason);
    if (o.signal) {
      if (o.signal.aborted) ac.abort(o.signal.reason);
      else o.signal.addEventListener("abort", onAbort, { once: true });
    }
    let timer: ReturnType<typeof setTimeout>;
    const timeoutErr = new WhisperError(`flow ${slug} timed out after ${timeoutMs}ms`, { status: 0 });
    timer = setTimeout(() => ac.abort(timeoutErr), timeoutMs);

    let resp: Response;
    try {
      resp = await f(url, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "text/event-stream",
          "user-agent": USER_AGENT,
          "x-whisper-client": USER_AGENT,
          "x-api-key": this.key,
        },
        body: JSON.stringify(body),
        signal: ac.signal,
      });
    } catch (err) {
      clearTimeout(timer);
      if (o.signal) o.signal.removeEventListener("abort", onAbort);
      if (err instanceof WhisperError) throw err;
      if (ac.signal.reason instanceof WhisperError) throw ac.signal.reason;
      const reason = (ac.signal.reason instanceof Error ? ac.signal.reason.message : undefined) ?? (err as Error)?.message;
      throw new WhisperError(`flow ${slug} unreachable: ${reason ?? "network error"}`, { status: 0 });
    }

    try {
      // A non-2xx is a JSON problem (AuthRequired / FlowNotFound / ...), not an event stream.
      if (resp.status >= 400) {
        const text = await readCappedText(resp);
        const b = (parseJson(text, "flow", resp.status) ?? {}) as Record<string, unknown>;
        const detail =
          typeof b.message === "string" ? b.message :
          typeof b.detail === "string" ? b.detail :
          `flow returned status ${resp.status}`;
        throw new WhisperError(detail, {
          status: resp.status,
          detail: typeof b.detail === "string" ? b.detail : undefined,
          title: typeof b.error === "string" ? b.error : undefined,
        });
      }
      return await this.aggregateSse(resp, slug, o);
    } finally {
      clearTimeout(timer);
      if (o.signal) o.signal.removeEventListener("abort", onAbort);
    }
  }

  /**
   * Consume an SSE Response into a {@link FlowResult}. A tiny line reader (zero deps): split
   * the stream on blank lines, read the `event:`/`data:` fields, and fold each event into
   * the aggregate (steps in order, a de-duplicated graph, the final presentation payload).
   * Prefers the streaming body reader; falls back to buffering the whole body where a
   * runtime does not expose a readable stream - both yield the identical aggregate.
   */
  private async aggregateSse(resp: Response, slug: string, o: RequestOptions): Promise<FlowResult> {
    const onEvent = o.onFlowEvent;
    const events: Array<{ event: string; data: unknown }> = [];
    const steps: FlowStep[] = [];
    const graph = { nodes: [] as Array<Record<string, unknown>>, edges: [] as Array<Record<string, unknown>> };
    const seenNodes = new Set<string>();
    const seenEdges = new Set<string>();
    let present: unknown;
    let totalLatencyMs: number | undefined;
    let runError: string | undefined;

    const handleBlock = (block: string) => {
      let event = "message";
      const dataLines: string[] = [];
      for (const line of block.split("\n")) {
        if (line.startsWith("event:")) event = line.slice(6).trim();
        else if (line.startsWith("data:")) dataLines.push(line.slice(5).replace(/^ /, ""));
      }
      const dataStr = dataLines.join("\n");
      if (dataStr === "") return;
      let data: unknown;
      try { data = JSON.parse(dataStr); } catch { data = dataStr; }
      events.push({ event, data });
      // A caller's observer must never break the run.
      try { onEvent?.(event, data); } catch { /* swallow */ }

      const d = (data && typeof data === "object" ? data : {}) as Record<string, unknown>;
      if (event === "step") {
        const id = String(d.id ?? "");
        // The internal presentation step carries the FormatOutput, not a table.
        if (id === "__present") { present = d.output; return; }
        steps.push({
          id,
          title: typeof d.title === "string" ? d.title : undefined,
          status: typeof d.status === "string" ? d.status : undefined,
          cypher: typeof d.cypher === "string" ? d.cypher : undefined,
          columns: Array.isArray(d.columns) ? d.columns.map((c) => String(c)) : undefined,
          rows: Array.isArray(d.rows) ? (d.rows as Array<Record<string, unknown>>) : undefined,
          output: d.output,
        });
      } else if (event === "graph") {
        const delta = (d.delta && typeof d.delta === "object" ? d.delta : {}) as { nodes?: unknown[]; edges?: unknown[] };
        for (const n of Array.isArray(delta.nodes) ? delta.nodes : []) {
          const node = (n && typeof n === "object" ? n : {}) as Record<string, unknown>;
          const nid = String(node.id ?? "");
          if (nid !== "" && seenNodes.has(nid)) continue;
          if (nid !== "") seenNodes.add(nid);
          graph.nodes.push(node);
        }
        for (const e of Array.isArray(delta.edges) ? delta.edges : []) {
          const edge = (e && typeof e === "object" ? e : {}) as Record<string, unknown>;
          const k = `${edge.from} ${edge.label ?? ""} ${edge.to}`;
          if (seenEdges.has(k)) continue;
          seenEdges.add(k);
          graph.edges.push(edge);
        }
      } else if (event === "complete") {
        if (typeof d.totalLatencyMs === "number") totalLatencyMs = d.totalLatencyMs;
      } else if (event === "error") {
        runError = typeof d.message === "string" ? d.message : "flow run failed";
      }
    };

    const body = resp.body as ReadableStream<Uint8Array> | null;
    if (body && typeof body.getReader === "function") {
      const reader = body.getReader();
      const decoder = new TextDecoder();
      let buf = "";
      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        buf += decoder.decode(value, { stream: true });
        const blocks = buf.split("\n\n");
        buf = blocks.pop() ?? "";
        for (const b of blocks) if (b.trim() !== "") handleBlock(b);
      }
      buf += decoder.decode();
      if (buf.trim() !== "") handleBlock(buf);
    } else {
      const text = await readCappedText(resp);
      for (const b of text.split("\n\n")) if (b.trim() !== "") handleBlock(b);
    }

    if (runError !== undefined) throw new WhisperError(`flow ${slug}: ${runError}`, { status: 502 });

    // The headline table is the last step that returned rows; else the last step.
    let anchor: FlowStep | null = null;
    for (let i = steps.length - 1; i >= 0; i--) {
      if ((steps[i].rows?.length ?? 0) > 0) { anchor = steps[i]; break; }
    }
    if (anchor === null && steps.length > 0) anchor = steps[steps.length - 1];

    return {
      slug,
      steps,
      anchor,
      columns: anchor?.columns ?? [],
      rows: anchor?.rows ?? [],
      graph,
      present,
      totalLatencyMs,
      events,
      status: resp.status,
    };
  }

  /**
   * Assess how resilient a country's core DNS is if it were cut off from the world.
   *
   * Could a country still resolve names if it were isolated? Counts how many of the 13 root
   * letters have in-country DNS_ROOT_INSTANCE anycast nodes, the Global-vs-Local split, the BGP
   * origin ASNs hosting them, and a resilience grade.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (anycast-dns-root-sovereignty) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Tunable params (pass as `params`): instanceType=ALL.
   * Headline columns: distinctLetters, totalInstances, globalCount, localCount, hostingAsns.
   *
   * @see https://www.whisper.security/docs/recipes/compliance
   */
  anycastDnsRootSovereignty(country: string = "BR", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("anycast-dns-root-sovereignty", { "country": country }, params, reqOpts);
  }

  /**
   * Find the choke points an attacker would target - and how any two things connect.
   *
   * From a starting foothold, finds shared dependencies whose compromise reaches furthest; for
   * any two indicators, traces how they are actually connected.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (attack-path) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Tunable params (pass as `params`): level=standard.
   * Headline columns: indicator, type, available, cached, found, score, level, explanation, factors, sources, advisory.
   *
   * @see https://www.whisper.security/docs/recipes/attack-path
   */
  attackPath(value: string = "paypal.com", other: string = "paypa1.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("attack-path", { "value": value, "other": other }, params, reqOpts);
  }

  /**
   * Map everything about a domain that's exposed to the outside world, scored for risk.
   *
   * Maps the full external footprint - subdomains, name/mail servers, registrant, third-party
   * services, connected web - and scores the exposure.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (attack-surface) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Tunable params (pass as `params`): level=standard.
   * Headline columns: indicator, type, available, cached, found, score, level, explanation, factors, sources, advisory.
   *
   * @see https://www.whisper.security/docs/recipes/pentest-recon
   */
  attackSurface(domain: string = "github.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("attack-surface", { "domain": domain }, params, reqOpts);
  }

  /**
   * Grade a network's routing security and trace conflicts to the domains they'd expose.
   *
   * Grades a network on the conflicts/gaps that make route hijacking possible, then traces any
   * conflict to the specific domains and organisations exposed on the affected blocks.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (bgp-hijack-exposure) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: prefix, is_moas, conflicting_asn.
   *
   * @see https://www.whisper.security/docs/recipes/bgp-routing
   */
  bgpHijackExposure(value: string = "AS13335", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("bgp-hijack-exposure", { "value": value }, params, reqOpts);
  }

  /**
   * Pick one asset and see what would break if it failed - and what it depends on in turn.
   *
   * Maps dependencies in both directions: everything that breaks if the asset fails (SPOFs) and
   * everything it relies on (its own DNS/mail/hosting/network supply chain).
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (blast-radius) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Tunable params (pass as `params`): depth=2.
   * Headline columns: labels, name.
   *
   * @see https://www.whisper.security/docs/recipes/soc
   */
  blastRadius(indicator: string = "ns1.dreamhost.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("blast-radius", { "indicator": indicator }, params, reqOpts);
  }

  /**
   * Assemble a ready-to-submit dossier for taking down a scam or phishing domain.
   *
   * One-pass takedown package: reputation verdict, owner (WHOIS), abuse-list listings, and
   * surrounding infrastructure, laid out ready to hand to a registrar/host.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (build-takedown-evidence-package) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: indicator, type, available, cached, found, score, level, explanation, factors, sources, advisory.
   *
   * @see https://www.whisper.security/docs/recipes/threat-intel
   */
  buildTakedownEvidencePackage(domain: string = "ickaoex.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("build-takedown-evidence-package", { "domain": domain }, params, reqOpts);
  }

  /**
   * Map an organisation's externally visible AI and agent endpoints from the outside.
   *
   * Maps externally visible AI/agent hosts (API, model, agent) from the outside via heuristic
   * hostname patterns (api./mcp./ai./vector./llm./agent./chat./copilot.). Best-effort leads.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (discover-ai-agent-infrastructure) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: hostname, ips.
   *
   * @see https://www.whisper.security/docs/recipes/pentest-recon
   */
  discoverAiAgentInfrastructure(value: string = "github.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("discover-ai-agent-infrastructure", { "value": value }, params, reqOpts);
  }

  /**
   * Investigate one suspicious domain, IP, or network in depth and get a clear picture of the threat and everything connected to it.
   *
   * Deep-dive: works outward across the whole footprint (related domains, real origins behind
   * CDN, neighbouring infra), threat-checks each node, never inherits maliciousness from shared
   * infra; labelled posture, no score.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (indicator) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: host, label, band, sub_labels, coverage, evidence.
   *
   * @see https://www.whisper.security/docs/recipes/soc
   */
  indicator(indicator: string = "theblackservicenetwork.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("indicator", { "indicator": indicator }, params, reqOpts);
  }

  /**
   * Turn one domain or IP into a full context card - owner, hosting, mail, location, reputation at a glance.
   *
   * Fills the picture for one indicator: registrant (WHOIS), hosting + country, mail/name
   * servers, network behind it, reputation read.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (indicator-enrichment) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: attribute, value.
   *
   * @see https://www.whisper.security/docs/recipes/dns-email
   */
  indicatorEnrichment(value: string = "google.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("indicator-enrichment", { "value": value }, params, reqOpts);
  }

  /**
   * Trace one indicator to its true owner and full estate, even behind privacy screens and CDNs.
   *
   * Works out the true operator (even behind privacy WHOIS), de-cloaks CDN-fronted sites to real
   * servers, pivots to the rest of that owner's estate across every layer.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (infrastructure-mapping) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Tunable params (pass as `params`): level=standard.
   * Headline columns: canonical_name, vendor_id, category, roles, host_class.
   *
   * @see https://www.whisper.security/docs/recipes/compliance
   */
  infrastructureMapping(value: string = "cloudflare.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("infrastructure-mapping", { "value": value }, params, reqOpts);
  }

  /**
   * Grade an organisation for over-reliance on single providers, regions, or facilities.
   *
   * Grades how concentrated infra is - too much riding on one provider/region/data-centre/cable
   * landing - surfacing SPOFs for resilience and DORA/NIS2 fourth-party risk.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (map-supply-chain-concentration) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: provider, asn, region, country.
   *
   * @see https://www.whisper.security/docs/recipes/compliance
   */
  mapSupplyChainConcentration(domain: string = "atlassian.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("map-supply-chain-concentration", { "domain": domain }, params, reqOpts);
  }

  /**
   * Check a domain's name servers for the misconfigurations that enable DNS hijacking.
   *
   * Audits delegation, flags stale/mismatched/lame nameservers, sizes each provider's share,
   * surfaces registry facts - catches delegation weakness before exploit.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (nameserver-hijack-dns-consistency) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: nameserver, ips, status.
   *
   * @see https://www.whisper.security/docs/recipes/dns-email
   */
  nameserverHijackDnsConsistency(value: string = "google.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("nameserver-hijack-dns-consistency", { "value": value }, params, reqOpts);
  }

  /**
   * Profile a network or address block into a full routing and reachability health card.
   *
   * Health card for a network/block: what it announces, peers/transit, single-upstream lean,
   * RPKI protection - the one-look reach & resilience report.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (route-health) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: prefix, multi_origin, anycast, withdrawn.
   *
   * @see https://www.whisper.security/docs/recipes/bgp-routing
   */
  routeHealth(target: string = "1.1.1.0/24", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("route-health", { "target": target }, params, reqOpts);
  }

  /**
   * Find subdomains that point at abandoned services an attacker could claim.
   *
   * Walks subdomains and flags ones aiming at deprovisioned targets (dangling CNAME whose target
   * no longer resolves) so you can reclaim/remove before someone else does. CNAME layer is
   * prod-ahead.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (subdomain-takeover) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: subdomain, ips.
   *
   * @see https://www.whisper.security/docs/recipes/pentest-recon
   */
  subdomainTakeover(value: string = "github.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("subdomain-takeover", { "value": value }, params, reqOpts);
  }

  /**
   * Find registered look-alikes of your brand and check which ones are dangerous.
   *
   * Finds registered impersonations across misspellings/risky TLDs, separates your own defensive
   * domains from strangers', flags fresh/privacy/abuse-listed ones into a prioritised list.
   *
   * KEYED. Multi-step FLOW: runs via the gallery runner (typosquat) over
   * SSE and aggregates the streamed steps into a FlowResult.
   * Headline columns: variant, method, confidence.
   *
   * @see https://www.whisper.security/docs/recipes/brand-protection
   */
  typosquat(domain: string = "paypal.com", params: FlowParams = {}, reqOpts?: RequestOptions): Promise<FlowResult> {
    return this.runFlow("typosquat", { "domain": domain }, params, reqOpts);
  }

  /**
   * Name the vendor and operator role behind a host or IP in one call.
   *
   * Resolves a host/IP to its canonical vendor, category and operator roles (DNS_OPERATOR / CDN
   * / ORIGIN_AS / MAIL_RECEIVER) with a confidence band.
   *
   * KEYED. Cypher: CALL whisper.identify([$v]) YIELD host, vendor_id, canonical_name, category, roles, host_class, band
   * Returns columns: host, vendor_id, canonical_name, category, roles, host_class, band.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures/identify
   */
  identify(v: string = "api.openai.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.identify([$v]) YIELD host, vendor_id, canonical_name, category, roles, host_class, band", { v: v }, reqOpts);
  }

  /**
   * Get a labelled threat posture for a host or IP - malicious, benign, or unknown.
   *
   * Returns a posture label + severity band + sub-labels + coverage + evidence for an indicator;
   * benign-allowlisted vs malicious-evidenced, never a bare score.
   *
   * KEYED. Cypher: CALL whisper.assess([$v]) YIELD host, label, band, sub_labels, coverage, evidence
   * Returns columns: host, label, band, sub_labels, coverage, evidence.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures
   */
  assess(v: string = "8.8.8.8", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.assess([$v]) YIELD host, label, band, sub_labels, coverage, evidence", { v: v }, reqOpts);
  }

  /**
   * Generate look-alike domain variants of a brand and see which are registered.
   *
   * Enumerates permutations (omission, bitsquatting, ...) of a domain, flags which exist, with a
   * per-variant confidence.
   *
   * KEYED. Cypher: CALL whisper.variants($v) YIELD variant, method, exists, confidence
   * Returns columns: variant, method, exists, confidence.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures/variants
   */
  variants(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.variants($v) YIELD variant, method, exists, confidence", { v: v }, reqOpts);
  }

  /**
   * Walk the graph to the nearest known vendors behind a host, with the channel and confidence.
   *
   * Structural attribution: returns nearest_known_vendors with the channel (DELEGATED_TO /
   * ORIGIN_AS) and confidence, plus siblings and coverage - explains WHY a host maps to a
   * vendor.
   *
   * KEYED. Cypher: CALL whisper.walk($v) YIELD coverage, host, nearest_known_vendors, no_atlas_match, siblings
   * Returns columns: coverage, host, nearest_known_vendors, no_atlas_match, siblings.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures
   */
  walk(v: string = "cloudflare.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.walk($v) YIELD coverage, host, nearest_known_vendors, no_atlas_match, siblings", { v: v }, reqOpts);
  }

  /**
   * Score an indicator against the threat feeds and explain exactly why.
   *
   * Threat-intel scorer: score + level + human explanation + the feeds it is listed in (feedId,
   * weight, firstSeen/lastSeen). Two live forms: bare CALL explain($v) (full columns) and CALL
   * whisper.explain($v) (restricted YIELD).
   *
   * KEYED. Cypher: CALL whisper.explain($v) YIELD indicator, score, level, explanation, sources
   * Returns columns: indicator, score, level, explanation, sources.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures/explain
   */
  explain(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.explain($v) YIELD indicator, score, level, explanation, sources", { v: v }, reqOpts);
  }

  /**
   * Reduce any hostname to its registrable apex (eTLD+1) via the Public Suffix List.
   *
   * PSL-correct eTLD+1: www.foo.co.uk -> foo.co.uk. The right way to group hosts by the thing
   * someone actually registered.
   *
   * KEYED. Cypher: CALL whisper.psl.tldPlusOne($v) YIELD apex
   * Returns columns: apex.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures/helpers
   */
  pslTldplusone(v: string = "www.foo.co.uk", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.psl.tldPlusOne($v) YIELD apex", { v: v }, reqOpts);
  }

  /**
   * Check whether a domain is a PSL private-section suffix and who submitted it.
   *
   * For a PSL private-section suffix, returns the submitting org/login and evidence kind +
   * confidence; found=false for ordinary registrable domains.
   *
   * KEYED. Cypher: CALL whisper.psl.affiliation($v) YIELD found, suffix, submitterOrg, submitterLogin, evidenceKind, confidence
   * Returns columns: found, suffix, submitterOrg, submitterLogin, evidenceKind, confidence.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures/helpers
   */
  pslAffiliation(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.psl.affiliation($v) YIELD found, suffix, submitterOrg, submitterLogin, evidenceKind, confidence", { v: v }, reqOpts);
  }

  /**
   * Find the real origin IPs behind a CDN-fronted domain, ranked by confidence.
   *
   * Candidate origin IPs behind a CDN with confidence, the methods that found them (e.g.
   * links_to), and the hosting ASN/name - de-cloaks to the real server.
   *
   * KEYED. Cypher: CALL whisper.origins($v) YIELD ip, confidence, methods, asn, asnName, kind
   * Returns columns: ip, confidence, methods, asn, asnName, kind.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures/origins
   */
  origins(v: string = "cloudflare.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.origins($v) YIELD ip, confidence, methods, asn, asnName, kind", { v: v }, reqOpts);
  }

  /**
   * Get the full historical WHOIS timeline for a domain.
   *
   * Every observed WHOIS snapshot over time: create/update/expiry, registrar, registrant,
   * country, nameservers - the ownership/registration story.
   *
   * KEYED. Cypher: CALL whisper.history($v)
   * Returns columns: indicator, type, queryTime, createDate, updateDate, expiryDate, registrar, registrant, country, nameServers, cached.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures/history
   */
  history(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.history($v)", { v: v }, reqOpts);
  }

  /**
   * Get the WHOIS-only historical timeline for a domain.
   *
   * The registration-record projection of the history timeline: create/update/expiry, registrar,
   * registrant, country, nameservers per snapshot.
   *
   * KEYED. Cypher: CALL whisper.history.whois($v) YIELD queryTime, createDate, updateDate, expiryDate, registrar, registrant, country, nameServers
   * Returns columns: queryTime, createDate, updateDate, expiryDate, registrar, registrant, country, nameServers.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures/history
   */
  historyWhois(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.history.whois($v) YIELD queryTime, createDate, updateDate, expiryDate, registrar, registrant, country, nameServers", { v: v }, reqOpts);
  }

  /**
   * List the member ASNs of an AS-SET macro.
   *
   * Expands an AS-SET name (e.g. AS-CLOUDFLARE) to its member ASNs and source RIR. Arg is a
   * STRING as-set name, not an integer ASN. (Membership is sparsely populated in the current
   * graph.)
   *
   * KEYED. Cypher: CALL whisper.asSet($v) YIELD asSetName, memberAsn, sourceRir
   * Returns columns: asSetName, memberAsn, sourceRir.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures
   */
  asset(v: string = "AS-CLOUDFLARE", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.asSet($v) YIELD asSetName, memberAsn, sourceRir", { v: v }, reqOpts);
  }

  /**
   * Check whether an IP is a known Tor exit relay.
   *
   * Live Tor exit-node check: found + fingerprint + exit-address count + source + ingest time
   * for an IPv4.
   *
   * KEYED. Cypher: CALL whisper.lookupTorRelay($v) YIELD indicator, found, fingerprint, exitAddressCount, source, ingestedAt
   * Returns columns: indicator, found, fingerprint, exitAddressCount, source, ingestedAt.
   *
   * @see https://www.whisper.security/docs/whisper-graph/procedures/helpers
   */
  lookupTorRelay(v: string = "185.220.101.33", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.lookupTorRelay($v) YIELD indicator, found, fingerprint, exitAddressCount, source, ingestedAt", { v: v }, reqOpts);
  }

  /**
   * List every node and relationship type in the graph with counts and examples.
   *
   * The self-describing schema: node/relationship types with counts, descriptions, examples,
   * source/target labels and query best-practices - the map of what the graph holds.
   *
   * KEYED. Cypher: CALL db.schema()
   * Returns columns: type, name, count, description, example, sourceLabels, targetLabels, fastPatterns, slowPatterns, bestPractices.
   *
   * @see https://www.whisper.security/docs/whisper-graph/schema
   */
  dbSchema(reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL db.schema()", {}, reqOpts);
  }

  /**
   * Contribute an indicator observation or feedback back into the graph (requires an API key).
   *
   * The write channel: submit an indicator/feedback with an attributable API key (anonymous
   * submits are refused to preserve K-anonymity). Keyed-only by design.
   *
   * KEYED. Cypher: CALL whisper.submit({kind:$kind, identifier_kind:$identifier_kind, value:$value})
   * Returns columns: observation_id, kind, accepted, idempotent, promotion_state, k_bucket, advisory, v.
   *
   * @see https://www.whisper.security/docs/cypher-api
   */
  submit(kind: string = "indicator", identifier_kind: string = "ip", value: string = "203.0.113.5", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.submit({kind:$kind, identifier_kind:$identifier_kind, value:$value})", { kind: kind, identifier_kind: identifier_kind, value: value }, reqOpts);
  }
}

/** Create a graph client bound to `apiKey`. Sugar for `new WhisperGraph(apiKey, opts)`. */
export function graph(apiKey: string, opts?: GraphOptions): WhisperGraph {
  return new WhisperGraph(apiKey, opts);
}
