// SPDX-License-Identifier: MIT
// Copyright (c) 2026 viaGraph B.V. (Whisper Security)
//
// GENERATED by scripts/gen-graph.mjs from the Whisper catalog. Do not edit by hand: change
// the catalog (or the generator) and re-run `node scripts/gen-graph.mjs`.
//
// The KEYED GRAPH namespace: the Whisper security graph, one typed method per catalog verb,
// POSTed to graph.whisper.security/api/query. It is Cypher, so it is KEYED (Kaveh's rule:
// if it is Cypher it needs an API key). This is the SAME auth path as the control plane,
// the key travels only as X-API-Key, never in a URL or a log. The keyless surface
// (verify / resolve / rdap) stays pure HTTPS and never touches this namespace.
//
// Wire shape: the graph endpoint replies { columns, rows, statistics } where each row is an
// OBJECT keyed by column name, so this namespace parses that object-row shape itself and
// returns a GraphResult; it does NOT route through the control-plane envelope decoder
// (that one expects array-rows and would silently mangle these results). Pure fetch, zero
// dependencies.

import { WhisperError, doFetch, parseJson, readCappedText } from "./http.js";
import { endpointsFor } from "./keyless.js";
import type { GraphParams, GraphResult, GraphStatistics, RequestOptions } from "./types.js";

const USER_AGENT = "whisper-edge/0.3";

/** Options for creating a graph client (same shape as the rest of the SDK). */
export interface GraphOptions extends RequestOptions {}

interface RawGraphBody {
  columns?: unknown;
  rows?: unknown;
  statistics?: unknown;
  detail?: unknown;
  title?: unknown;
}

/** Normalise the graph endpoint's object-row envelope into a {@link GraphResult}. */
function decodeGraph(body: unknown, status: number): GraphResult {
  const o = (body && typeof body === "object" ? body : {}) as RawGraphBody;
  const columns = Array.isArray(o.columns) ? o.columns.map((c) => String(c)) : [];
  const rows = Array.isArray(o.rows)
    ? o.rows.map((r) => (r && typeof r === "object" && !Array.isArray(r) ? (r as Record<string, unknown>) : { value: r }))
    : [];
  const statistics = (o.statistics && typeof o.statistics === "object" ? o.statistics : {}) as GraphStatistics;
  return { columns, rows, statistics, raw: body, status };
}

/**
 * The Whisper security graph, authenticated with an owner API key. Every method runs one
 * catalog verb against /api/query and returns a {@link GraphResult}. Direct verbs POST a
 * parameterised Cypher read; flow verbs (multi-step workflows) throw a clear 501 until the
 * workflow runner is exposed here, so nothing blocks. Reachable both standalone via
 * graph(key) and as control(key).graph, bound to the same key.
 */
export class WhisperGraph {
  private readonly key: string;
  private readonly opts: GraphOptions;

  constructor(apiKey: string, opts: GraphOptions = {}) {
    const k = (apiKey ?? "").trim();
    if (k === "") {
      throw new WhisperError("no API key, the graph is keyed, pass your whisper_live_ key (never hard-code it; read it from the environment)", { status: 401 });
    }
    this.key = k;
    this.opts = opts;
  }

  private merge(extra?: RequestOptions): RequestOptions {
    return { ...this.opts, ...extra, endpoints: { ...this.opts.endpoints, ...extra?.endpoints } };
  }

  /**
   * POST a parameterised Cypher read to the graph endpoint and decode the object-row
   * envelope. `params` are bound server-side as $-parameters (never spliced into the query),
   * so a value can never break out of the Cypher, however hostile. The key rides only as
   * the X-API-Key header. Any >=400 status surfaces the server's clear detail as a
   * WhisperError (Postel: a clear error, never an opaque 500).
   */
  private async runDirect(cypher: string, params: GraphParams, reqOpts?: RequestOptions): Promise<GraphResult> {
    const o = this.merge(reqOpts);
    const url = endpointsFor(o).control;
    const resp = await doFetch(
      url,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "application/json",
          "user-agent": USER_AGENT,
          "x-api-key": this.key,
        },
        body: JSON.stringify({ query: cypher, parameters: params }),
      },
      o,
      "graph",
    );
    const text = await readCappedText(resp);
    const body = parseJson(text, "graph", resp.status);
    if (resp.status >= 400) {
      const p = (body && typeof body === "object" ? body : {}) as Record<string, unknown>;
      const detail = typeof p.detail === "string" ? p.detail : typeof p.title === "string" ? p.title : `graph returned status ${resp.status}`;
      throw new WhisperError(detail, {
        status: resp.status,
        detail: typeof p.detail === "string" ? p.detail : undefined,
        title: typeof p.title === "string" ? p.title : undefined,
        type: typeof p.type === "string" ? p.type : undefined,
      });
    }
    return decodeGraph(body, resp.status);
  }

  /**
   * The raw escape hatch: run an arbitrary Cypher read against the graph with your own
   * `params` (bound as $-parameters). KEYED. Use this for any verb this SDK stubs (a flow
   * workflow, or submit's full field set) or for a query the catalog does not name.
   */
  query(cypher: string, params: GraphParams = {}, reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect(cypher, params, reqOpts);
  }

  /**
   * Assess how resilient a country's core DNS is if it were cut off from the world.
   *
   * Could a country still resolve names if it were isolated? Counts how many of the 13 root
   * letters have in-country DNS_ROOT_INSTANCE anycast nodes, the Global-vs-Local split, the BGP
   * origin ASNs hosting them, and a resilience grade.
   *
   * KEYED. Runs via the workflow runner: run_workflow (anycast-dns-root-sovereignty).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: distinctLetters, totalInstances, globalCount, localCount, hostingAsns.
   */
  anycastDnsRootSovereignty(country: string = "BR", reqOpts?: RequestOptions): Promise<GraphResult> {
    void country; void reqOpts;
    return Promise.reject(new WhisperError("anycastDnsRootSovereignty runs via the workflow runner (run_workflow (anycast-dns-root-sovereignty)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Find the choke points an attacker would target - and how any two things connect.
   *
   * From a starting foothold, finds shared dependencies whose compromise reaches furthest; for
   * any two indicators, traces how they are actually connected.
   *
   * KEYED. Runs via the workflow runner: run_workflow (attack-path).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: indicator, type, available, cached, found, score, level, explanation, factors, sources, advisory.
   */
  attackPath(value: string = "paypal.com", other: string = "paypa1.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void value; void other; void reqOpts;
    return Promise.reject(new WhisperError("attackPath runs via the workflow runner (run_workflow (attack-path)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Map everything about a domain that's exposed to the outside world, scored for risk.
   *
   * Maps the full external footprint - subdomains, name/mail servers, registrant, third-party
   * services, connected web - and scores the exposure.
   *
   * KEYED. Runs via the workflow runner: run_workflow (attack-surface).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: indicator, type, available, cached, found, score, level, explanation, factors, sources, advisory.
   */
  attackSurface(domain: string = "github.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void domain; void reqOpts;
    return Promise.reject(new WhisperError("attackSurface runs via the workflow runner (run_workflow (attack-surface)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Grade a network's routing security and trace conflicts to the domains they'd expose.
   *
   * Grades a network on the conflicts/gaps that make route hijacking possible, then traces any
   * conflict to the specific domains and organisations exposed on the affected blocks.
   *
   * KEYED. Runs via the workflow runner: run_workflow (bgp-hijack-exposure).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: prefix, is_moas, conflicting_asn.
   */
  bgpHijackExposure(value: string = "AS13335", reqOpts?: RequestOptions): Promise<GraphResult> {
    void value; void reqOpts;
    return Promise.reject(new WhisperError("bgpHijackExposure runs via the workflow runner (run_workflow (bgp-hijack-exposure)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Pick one asset and see what would break if it failed - and what it depends on in turn.
   *
   * Maps dependencies in both directions: everything that breaks if the asset fails (SPOFs) and
   * everything it relies on (its own DNS/mail/hosting/network supply chain).
   *
   * KEYED. Runs via the workflow runner: run_workflow (blast-radius).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: labels, name.
   */
  blastRadius(indicator: string = "ns1.dreamhost.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void indicator; void reqOpts;
    return Promise.reject(new WhisperError("blastRadius runs via the workflow runner (run_workflow (blast-radius)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Assemble a ready-to-submit dossier for taking down a scam or phishing domain.
   *
   * One-pass takedown package: reputation verdict, owner (WHOIS), abuse-list listings, and
   * surrounding infrastructure, laid out ready to hand to a registrar/host.
   *
   * KEYED. Runs via the workflow runner: run_workflow (build-takedown-evidence-package).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: indicator, type, available, cached, found, score, level, explanation, factors, sources, advisory.
   */
  buildTakedownEvidencePackage(domain: string = "ickaoex.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void domain; void reqOpts;
    return Promise.reject(new WhisperError("buildTakedownEvidencePackage runs via the workflow runner (run_workflow (build-takedown-evidence-package)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Map an organisation's externally visible AI and agent endpoints from the outside.
   *
   * Maps externally visible AI/agent hosts (API, model, agent) from the outside via heuristic
   * hostname patterns (api./mcp./ai./vector./llm./agent./chat./copilot.). Best-effort leads.
   *
   * KEYED. Runs via the workflow runner: run_workflow (discover-ai-agent-infrastructure).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: hostname, ips.
   */
  discoverAiAgentInfrastructure(value: string = "github.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void value; void reqOpts;
    return Promise.reject(new WhisperError("discoverAiAgentInfrastructure runs via the workflow runner (run_workflow (discover-ai-agent-infrastructure)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Investigate one suspicious domain, IP, or network in depth and get a clear picture of the threat and everything connected to it.
   *
   * Deep-dive: works outward across the whole footprint (related domains, real origins behind
   * CDN, neighbouring infra), threat-checks each node, never inherits maliciousness from shared
   * infra; labelled posture, no score.
   *
   * KEYED. Runs via the workflow runner: run_workflow (indicator).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: host, label, band, sub_labels, coverage, evidence.
   */
  indicator(indicator: string = "theblackservicenetwork.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void indicator; void reqOpts;
    return Promise.reject(new WhisperError("indicator runs via the workflow runner (run_workflow (indicator)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Turn one domain or IP into a full context card - owner, hosting, mail, location, reputation at a glance.
   *
   * Fills the picture for one indicator: registrant (WHOIS), hosting + country, mail/name
   * servers, network behind it, reputation read.
   *
   * KEYED. Runs via the workflow runner: run_workflow (indicator-enrichment).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: attribute, value.
   */
  indicatorEnrichment(value: string = "google.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void value; void reqOpts;
    return Promise.reject(new WhisperError("indicatorEnrichment runs via the workflow runner (run_workflow (indicator-enrichment)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Trace one indicator to its true owner and full estate, even behind privacy screens and CDNs.
   *
   * Works out the true operator (even behind privacy WHOIS), de-cloaks CDN-fronted sites to real
   * servers, pivots to the rest of that owner's estate across every layer.
   *
   * KEYED. Runs via the workflow runner: run_workflow (infrastructure-mapping).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: canonical_name, vendor_id, category, roles, host_class.
   */
  infrastructureMapping(value: string = "cloudflare.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void value; void reqOpts;
    return Promise.reject(new WhisperError("infrastructureMapping runs via the workflow runner (run_workflow (infrastructure-mapping)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Grade an organisation for over-reliance on single providers, regions, or facilities.
   *
   * Grades how concentrated infra is - too much riding on one provider/region/data-centre/cable
   * landing - surfacing SPOFs for resilience and DORA/NIS2 fourth-party risk.
   *
   * KEYED. Runs via the workflow runner: run_workflow (map-supply-chain-concentration).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: provider, asn, region, country.
   */
  mapSupplyChainConcentration(domain: string = "atlassian.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void domain; void reqOpts;
    return Promise.reject(new WhisperError("mapSupplyChainConcentration runs via the workflow runner (run_workflow (map-supply-chain-concentration)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Check a domain's name servers for the misconfigurations that enable DNS hijacking.
   *
   * Audits delegation, flags stale/mismatched/lame nameservers, sizes each provider's share,
   * surfaces registry facts - catches delegation weakness before exploit.
   *
   * KEYED. Runs via the workflow runner: run_workflow (nameserver-hijack-dns-consistency).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: nameserver, ips, status.
   */
  nameserverHijackDnsConsistency(value: string = "google.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void value; void reqOpts;
    return Promise.reject(new WhisperError("nameserverHijackDnsConsistency runs via the workflow runner (run_workflow (nameserver-hijack-dns-consistency)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Profile a network or address block into a full routing and reachability health card.
   *
   * Health card for a network/block: what it announces, peers/transit, single-upstream lean,
   * RPKI protection - the one-look reach & resilience report.
   *
   * KEYED. Runs via the workflow runner: run_workflow (route-health).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: prefix, multi_origin, anycast, withdrawn.
   */
  routeHealth(target: string = "1.1.1.0/24", reqOpts?: RequestOptions): Promise<GraphResult> {
    void target; void reqOpts;
    return Promise.reject(new WhisperError("routeHealth runs via the workflow runner (run_workflow (route-health)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Find subdomains that point at abandoned services an attacker could claim.
   *
   * Walks subdomains and flags ones aiming at deprovisioned targets (dangling CNAME whose target
   * no longer resolves) so you can reclaim/remove before someone else does. CNAME layer is
   * prod-ahead.
   *
   * KEYED. Runs via the workflow runner: run_workflow (subdomain-takeover).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: subdomain, ips.
   */
  subdomainTakeover(value: string = "github.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void value; void reqOpts;
    return Promise.reject(new WhisperError("subdomainTakeover runs via the workflow runner (run_workflow (subdomain-takeover)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Find registered look-alikes of your brand and check which ones are dangerous.
   *
   * Finds registered impersonations across misspellings/risky TLDs, separates your own defensive
   * domains from strangers', flags fresh/privacy/abuse-listed ones into a prioritised list.
   *
   * KEYED. Runs via the workflow runner: run_workflow (typosquat).
   * Not yet exposed as a raw Cypher read over /api/query, so this method
   * throws a clear WhisperError (501). Use graph.query() for a direct read.
   * When wired it will return columns: variant, method, confidence.
   */
  typosquat(domain: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    void domain; void reqOpts;
    return Promise.reject(new WhisperError("typosquat runs via the workflow runner (run_workflow (typosquat)), not a raw Cypher read; it is not yet exposed over /api/query. Use the console/agent run endpoint, or graph.query() for a direct read.", { status: 501 }));
  }

  /**
   * Name the vendor and operator role behind a host or IP in one call.
   *
   * Resolves a host/IP to its canonical vendor, category and operator roles (DNS_OPERATOR / CDN
   * / ORIGIN_AS / MAIL_RECEIVER) with a confidence band.
   *
   * KEYED. Cypher: CALL whisper.identify([$v]) YIELD host, vendor_id, canonical_name, category, roles, host_class, band
   * Returns columns: host, vendor_id, canonical_name, category, roles, host_class, band.
   */
  identify(v: string = "api.openai.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.identify([$v]) YIELD host, vendor_id, canonical_name, category, roles, host_class, band", { v: v }, reqOpts);
  }

  /**
   * Get a labelled threat posture for a host or IP - malicious, benign, or unknown.
   *
   * Returns a posture label + severity band + sub-labels + coverage + evidence for an indicator;
   * benign-allowlisted vs malicious-evidenced, never a bare score.
   *
   * KEYED. Cypher: CALL whisper.assess([$v]) YIELD host, label, band, sub_labels, coverage, evidence
   * Returns columns: host, label, band, sub_labels, coverage, evidence.
   */
  assess(v: string = "8.8.8.8", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.assess([$v]) YIELD host, label, band, sub_labels, coverage, evidence", { v: v }, reqOpts);
  }

  /**
   * Generate look-alike domain variants of a brand and see which are registered.
   *
   * Enumerates permutations (omission, bitsquatting, ...) of a domain, flags which exist, with a
   * per-variant confidence.
   *
   * KEYED. Cypher: CALL whisper.variants($v) YIELD variant, method, exists, confidence
   * Returns columns: variant, method, exists, confidence.
   */
  variants(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.variants($v) YIELD variant, method, exists, confidence", { v: v }, reqOpts);
  }

  /**
   * Walk the graph to the nearest known vendors behind a host, with the channel and confidence.
   *
   * Structural attribution: returns nearest_known_vendors with the channel (DELEGATED_TO /
   * ORIGIN_AS) and confidence, plus siblings and coverage - explains WHY a host maps to a
   * vendor.
   *
   * KEYED. Cypher: CALL whisper.walk($v) YIELD coverage, host, nearest_known_vendors, no_atlas_match, siblings
   * Returns columns: coverage, host, nearest_known_vendors, no_atlas_match, siblings.
   */
  walk(v: string = "cloudflare.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.walk($v) YIELD coverage, host, nearest_known_vendors, no_atlas_match, siblings", { v: v }, reqOpts);
  }

  /**
   * Score an indicator against the threat feeds and explain exactly why.
   *
   * Threat-intel scorer: score + level + human explanation + the feeds it is listed in (feedId,
   * weight, firstSeen/lastSeen). Two live forms: bare CALL explain($v) (full columns) and CALL
   * whisper.explain($v) (restricted YIELD).
   *
   * KEYED. Cypher: CALL whisper.explain($v) YIELD indicator, score, level, explanation, sources
   * Returns columns: indicator, score, level, explanation, sources.
   */
  explain(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.explain($v) YIELD indicator, score, level, explanation, sources", { v: v }, reqOpts);
  }

  /**
   * Reduce any hostname to its registrable apex (eTLD+1) via the Public Suffix List.
   *
   * PSL-correct eTLD+1: www.foo.co.uk -> foo.co.uk. The right way to group hosts by the thing
   * someone actually registered.
   *
   * KEYED. Cypher: CALL whisper.psl.tldPlusOne($v) YIELD apex
   * Returns columns: apex.
   */
  pslTldplusone(v: string = "www.foo.co.uk", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.psl.tldPlusOne($v) YIELD apex", { v: v }, reqOpts);
  }

  /**
   * Check whether a domain is a PSL private-section suffix and who submitted it.
   *
   * For a PSL private-section suffix, returns the submitting org/login and evidence kind +
   * confidence; found=false for ordinary registrable domains.
   *
   * KEYED. Cypher: CALL whisper.psl.affiliation($v) YIELD found, suffix, submitterOrg, submitterLogin, evidenceKind, confidence
   * Returns columns: found, suffix, submitterOrg, submitterLogin, evidenceKind, confidence.
   */
  pslAffiliation(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.psl.affiliation($v) YIELD found, suffix, submitterOrg, submitterLogin, evidenceKind, confidence", { v: v }, reqOpts);
  }

  /**
   * Find the real origin IPs behind a CDN-fronted domain, ranked by confidence.
   *
   * Candidate origin IPs behind a CDN with confidence, the methods that found them (e.g.
   * links_to), and the hosting ASN/name - de-cloaks to the real server.
   *
   * KEYED. Cypher: CALL whisper.origins($v) YIELD ip, confidence, methods, asn, asnName, kind
   * Returns columns: ip, confidence, methods, asn, asnName, kind.
   */
  origins(v: string = "cloudflare.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.origins($v) YIELD ip, confidence, methods, asn, asnName, kind", { v: v }, reqOpts);
  }

  /**
   * Get the full historical WHOIS timeline for a domain.
   *
   * Every observed WHOIS snapshot over time: create/update/expiry, registrar, registrant,
   * country, nameservers - the ownership/registration story.
   *
   * KEYED. Cypher: CALL whisper.history($v)
   * Returns columns: indicator, type, queryTime, createDate, updateDate, expiryDate, registrar, registrant, country, nameServers, cached.
   */
  history(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.history($v)", { v: v }, reqOpts);
  }

  /**
   * Get the WHOIS-only historical timeline for a domain.
   *
   * The registration-record projection of the history timeline: create/update/expiry, registrar,
   * registrant, country, nameservers per snapshot.
   *
   * KEYED. Cypher: CALL whisper.history.whois($v) YIELD queryTime, createDate, updateDate, expiryDate, registrar, registrant, country, nameServers
   * Returns columns: queryTime, createDate, updateDate, expiryDate, registrar, registrant, country, nameServers.
   */
  historyWhois(v: string = "paypal.com", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.history.whois($v) YIELD queryTime, createDate, updateDate, expiryDate, registrar, registrant, country, nameServers", { v: v }, reqOpts);
  }

  /**
   * List the member ASNs of an AS-SET macro.
   *
   * Expands an AS-SET name (e.g. AS-CLOUDFLARE) to its member ASNs and source RIR. Arg is a
   * STRING as-set name, not an integer ASN. (Membership is sparsely populated in the current
   * graph.)
   *
   * KEYED. Cypher: CALL whisper.asSet($v) YIELD asSetName, memberAsn, sourceRir
   * Returns columns: asSetName, memberAsn, sourceRir.
   */
  asset(v: string = "AS-CLOUDFLARE", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.asSet($v) YIELD asSetName, memberAsn, sourceRir", { v: v }, reqOpts);
  }

  /**
   * Check whether an IP is a known Tor exit relay.
   *
   * Live Tor exit-node check: found + fingerprint + exit-address count + source + ingest time
   * for an IPv4.
   *
   * KEYED. Cypher: CALL whisper.lookupTorRelay($v) YIELD indicator, found, fingerprint, exitAddressCount, source, ingestedAt
   * Returns columns: indicator, found, fingerprint, exitAddressCount, source, ingestedAt.
   */
  lookupTorRelay(v: string = "185.220.101.33", reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL whisper.lookupTorRelay($v) YIELD indicator, found, fingerprint, exitAddressCount, source, ingestedAt", { v: v }, reqOpts);
  }

  /**
   * List every node and relationship type in the graph with counts and examples.
   *
   * The self-describing schema: node/relationship types with counts, descriptions, examples,
   * source/target labels and query best-practices - the map of what the graph holds.
   *
   * KEYED. Cypher: CALL db.schema()
   * Returns columns: type, name, count, description, example, sourceLabels, targetLabels, fastPatterns, slowPatterns, bestPractices.
   */
  dbSchema(reqOpts?: RequestOptions): Promise<GraphResult> {
    return this.runDirect("CALL db.schema()", {}, reqOpts);
  }

  /**
   * Contribute an indicator observation or feedback back into the graph (requires an API key).
   *
   * The write channel: submit an indicator/feedback with an attributable API key (anonymous
   * submits are refused to preserve K-anonymity). Keyed-only by design.
   *
   * KEYED. The full parameter set for this write is not yet enumerated in the
   * catalog, so this method throws a clear WhisperError (501). Use graph.query()
   * with your own Cypher, or the console run endpoint.
   */
  submit(kind: string = "indicator", reqOpts?: RequestOptions): Promise<GraphResult> {
    void kind; void reqOpts;
    return Promise.reject(new WhisperError("submit: the full parameter set for this call is not yet enumerated in the catalog. Use graph.query() with your own Cypher, or the console run endpoint.", { status: 501 }));
  }
}

/** Create a graph client bound to `apiKey`. Sugar for `new WhisperGraph(apiKey, opts)`. */
export function graph(apiKey: string, opts?: GraphOptions): WhisperGraph {
  return new WhisperGraph(apiKey, opts);
}
